version: '2'
services:
  tomcat:
    build:
      context: ./
      dockerfile: Dockerfile.alp
    ports:
      - "8080:8080"
    volumes:
      - war-volume:/usr/local/tomcat/webapps/
  war:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - war-volume:/usr/local/tomcat/webapps/

volumes:
  war-volume:
  #Pass, Dmitry
